### ISSUE TITLE
Uniform Vec2 UVOffset in SpriteRendering is not always 100% accurate when the camera is in certain positions

### ISSUE THREAD

**Issue by Elaviers** [ELAVIERS/CPP-Roguelike#2]

**Comment by ELAVIERS** [comment]
Fixed : Projectiles render using drawSprite now.

**Comment by Elaviers** [comment]
Issue still occurs on things rendered with SpriteRenderer..

![image](https://cloud.githubusercontent.com/assets/5192086/24690656/1b83ba62-1983-11e7-9bfb-9f45f079ac4e.png)

**Comment by Elaviers** [comment]
Resolved by fixing truncation issues.
